name: Integration Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: test
        run: |
          # build image
          ./gradlew clean :integration-test:app:jibDockerBuild

          # start containers
          docker compose -f integration-test/docker-compose.yaml up -d --wait

          # do test
          ./gradlew :integration-test:testing:test

      - name: report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
