name: Publish to Maven Central Repository

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: set up Gradle properties
        shell: bash
        env:
          PUBLICATION_PROPERTIES: ${{ secrets.PUBLICATION_PROPERTIES }}
        run: echo "$PUBLICATION_PROPERTIES" >> gradle.properties

      - name: publish
        run: ./gradlew :core:clean :core:publishAndReleaseToMavenCentral --no-configuration-cache
